version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
permissions:
  - object: /var/www/
    owner: ec2-user
    group: ec2-user
    mode: 777
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

